# Generated by Django 3.2.23 on 2024-10-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241015_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
